# JPA CONFIG
spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://172.17.0.2:3306/algamoney_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: password
---
# SPRING JACKSON CONFIG
spring:

  jackson:
    deserialization:
      fail-on-unknown-properties: true
---
#OAUTH2 AUTH SERVER
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jws-algorithm: RSA
          issuer-uri: http://127.0.0.1:9090
          jwk-set-uri: http://127.0.0.1:9090/oauth2/jwks
---
  #LOGGING
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: TRACE
    org.springframework.security.oauth2: INFO